apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-secret
    namespace: homelab-web
type: Opaque
data:
    OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:txjQs2zotnFICrJpbN5ICpNfGV6WZdExS4Z2Mg==,iv:HkVyTtL+c1UnSk95aIE08nIZnMBmscAG+nFToSJ/Xxk=,tag:8cqJqgfez7xm2VagM7V6SA==,type:str]
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:/kEZVnLcUe1wDF+Iutog+PnKAwRgZuTEbOH23pSBblkhLV7uJRORJoQK1bD69P8aJvxYLCA1cuI=,iv:9F9BH5Y0G9aGc/IPlx6RlYxDLpS4pNyReffsw8nK9bI=,tag:9e+2uRQb3pNM6zykZSssuA==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:syIbjlMfQ9K4b1jGcgTdjjWNz7wp+1FioKdSds2FGHlS+CWNIWbECV93S49Q4VyXEOubUemUUQjizo9d,iv:CmAf6ZOq5UzM7bwjibfByjjAHaGx1Sj7K1kkK8eAR54=,tag:4DthH7nhfqcq/3k4DkmvYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ufd3ltyyp6pwjsxp3teszwyf24scyu9jwszhyl3gzu2eh52wjyys7v8una
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZVJVMkJlZTRtendvSHFp
            YXJSdlFHQ05sb3FNb2tZL1BkN01QVWFRVEM0ClZqV1BuOEZ5Zlh2ZVpaUncxbTNR
            UzJaZURFRlpZNGNjai90QnlPdUFXUlUKLS0tIFhUdjNPV0pxRENkWmJpZVEyL3Zv
            cDU0MXBYU0o4LzQwOEdjR2Q5WEF2b1UKbFF84j53g08lZu+1k+O7arkGbPPPU4Hk
            D8ZL8avlPWSbrZuB0aJcwyqzMhyvjNaFja7NeRf/HwUfrpXOtMiYAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T11:24:47Z"
    mac: ENC[AES256_GCM,data:kFQ3wEAn3jGu/OnrnAp65DmMTngpnJvW1F/HSyVX+Af+oAWYLG/fdh2zaYZfv7IKV0jK647eqjkC550HwfMawicT28zeR3ogtXjoP2puWdG5lTzrbxnoDW8714zIN7pbeMpDfBhrC6tUKTjH71sfJcW6JnyYXay91wf7jx3m7RY=,iv:JoPsRv0J/4w+/jqIB8bNZNdQPEW2yxxN2em5JgAyssM=,tag:6AvUifHU8EsNv6vpA4yIjw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
