apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-secret
    namespace: homelab-web
type: Opaque
data:
    OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:ppXPD6L7OlStDPPvDUy+AoMrq5o563F5u79TfA==,iv:Mud39tRN+7qdbtTFtf360qTAYQtlEmpnnIzpRG+JgtY=,tag:VlRr+0vIw9hbB597GRTC7w==,type:str]
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:ixT6qjZrMhg9xk32FBUR8dyYuj2kHieCXY8mDO6WSJlB8TIH3MIAik0U69o0lPQcZc3TmT3t5CU=,iv:7R2q4+fAo4VQDSomzh8x8Wyci+yfC+IWp+t/j/f6PfI=,tag:MHmJAgi2xADYAankhAwEAA==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:Ww29MGTWMRvmvcdEi1maRhvlgjzyKrW30naXw9+D1P0hjbVQG2BtkSctouk=,iv:K4lvkDPIS8EHTAG25AvJq5rRRF6Tw+BjJ7V5bAR24po=,tag:lB19YpxsI92uU3zbeuyZjA==,type:str]
sops:
    age:
        - recipient: age1ufd3ltyyp6pwjsxp3teszwyf24scyu9jwszhyl3gzu2eh52wjyys7v8una
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ekM3OHA3NnpPaFk1bGJk
            dFJhZU16UFdzdXV1eVRmUFpVV2hWY2svZkhFCmVoTDhMM1RJNy9nZHk1cWdHYlF6
            MkpqcFF5UWp5RlFDOEVlcWNjSHdoVmcKLS0tIDZkbUV0MW5ycHJUakFjMVlweXRS
            dzNUakR4eFZUdXpXT3owUFFKWVU1YW8KHtkb3wH/nW399ODfQubsUaAVrkqowqgZ
            tcrY0mWfbOTyL/RkpGZMBTdTJO8gv9Xkgn0njBne/JvjxngBwsiIhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T16:46:52Z"
    mac: ENC[AES256_GCM,data:O6u8JpxABuKocwDevODoFbgv7bbjEfmOsW0qEWMVsz7cAUGlSLGvRPdh/8ur/b+MHx6TjUVimOCkJC+ZedUyrFSxUHio1aIzo/VjYJ8vWQjyu04rXlNvRQQK8Hmgb2Awma+kVEjqHY+KFqCRGV6j4DgOUWcLWYvmHwoSH60KOK0=,iv:X1CsBJpOm8neY5/SXa5YEXbLIbYG6qxamA33GJRAdV4=,tag:q+IcTH3IA2QjiIFNiW8/EQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
