apiVersion: apps/v1
kind: Deployment
metadata:
  name: homelab-web
  namespace: homelab-web
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: web
          image: ghcr.io/wlodzimierrr/homelab-web:sha-fe815dbfaf2070c82854adf0b880e56c9f92ee69
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 256Mi
