apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress-http.yaml
  - networkpolicy-allow-acme-http01-solver.yaml
commonLabels:
  homelab.env: dev
patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml
