apiVersion: apps/v1
kind: Deployment
metadata:
  name: mozi
  namespace: mozi
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mozi
      homelab.env: dev
  template:
    spec:
      containers:
        - name: web
          image: ghcr.io/wlodzimierrr/mozi:sha-8cc0024d15fc955d66d4259310cca681e58688b9
          imagePullPolicy: Always
          env:
            - name: APP_ENV
              value: dev
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 256Mi
