apiVersion: v1
kind: Secret
metadata:
    name: homelab-api-ghcr-read
    namespace: homelab-api
type: Opaque
stringData:
    GHCR_READ_TOKEN: ENC[AES256_GCM,data:AI0+wEUEgrQD+E3SUFbfjH9qrOwZ0yPOD+eEu8FovpAGCYbSFyRhRA==,iv:ZLS39K89GE1iWf3ukQZr0AecgYsZOovJPugTTdQrS2Y=,tag:i61RnsJFvfPbhrTrLD109A==,type:str]
sops:
    age:
        - recipient: age1ufd3ltyyp6pwjsxp3teszwyf24scyu9jwszhyl3gzu2eh52wjyys7v8una
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdndKakVCY1JudkNGKzBZ
            STRsRGl6MDdFUGszZXdvMEozKzFocFJLemkwCmNyeUk4SmtaVTR2NEwvV2F0dWpj
            MU1PblNhZDdkRFpNM21PVUJUdmREOWsKLS0tIHFUeWYyaEVSRHFmTDl1R20vT1Zz
            dmpuVFVYWWdmYS80aWltVlZBRjVGWFkKqZBkimkv9FmNksgukZzaVGFJ+braetGh
            LsOz1uBy4n8vrga6h3gEmHfmifJSeA+gsa2txjsACMREtw3TS7mYLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T12:34:57Z"
    mac: ENC[AES256_GCM,data:kGIRVzu5XyBkZqkaLqzRcXnapYd1VdXV9ZMLwNJ6g7Aa8bk8Br8Ye/rrWzBDhsW6wEEkjZrlTsivwKLKmvTRK6jkLuwP3klXpG9jF6XU+yw2/qKorrG6+eiLew/pN14d8thyR1q6Xia1PpQ/b+opdqI8/w9bCzyJl/E302LO2wE=,iv:58UKGL6Gn9ymrpvopiH7htxZ/GC6Zaii+YmSu3/QrWo=,tag:OzTzZ7ZlTKZ2oE1mXYMd3g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
