apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: git-github-token-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - git-github-token-secret.enc.yaml
