apiVersion: v1
kind: Secret
metadata:
    name: homelab-api-git-github
    namespace: homelab-api
type: Opaque
stringData:
    GIT_GITHUB_TOKEN: ENC[AES256_GCM,data:wHKklVAv+hY0O+GWIXn/i48t80vLwqyauRgqcuAmbYlrQfY9jKRpbvzH4inT9JQf440+tcDJH6bpTEJd+WcGWcajljv/nRzAS10mlZb/EHnGuuG94PoXf2Q24kd4,iv:E7CpiT/PFZMaAiGFWgaTmQl9MxHGr9AgkLHYt8tByxI=,tag:UyH8wDnyZW+pDNqYoldD3g==,type:str]
sops:
    age:
        - recipient: age1ufd3ltyyp6pwjsxp3teszwyf24scyu9jwszhyl3gzu2eh52wjyys7v8una
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvbkUwOWNhUXdsd3p6SExL
            bVZJUzdOY0dtQno0czRSRUFlMVd0REJLU1FrCmhTbWxHT0wvTTVwQ0s1MmZaQnhW
            ajQ1OEh5NkRLcGlteG9UdVdqVmcxSTAKLS0tIENVcDBhRzB2RjEyWnNCem9yMEp5
            a1lnVElFTnZWWmsvdXViRGNwWEpFZ28K165dmppFinoQ1jBPjB1xF+M3BcRvYp/n
            H4XnyJZU0CPjyRHzQ9VE1rBbhfkFTHEFc033ei78s6CSN2LBTbdDXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T09:50:00Z"
    mac: ENC[AES256_GCM,data:8a0NgWf+AY8uEOiHzR7aVqusGIQu70qWlq/JasBAvHuG76ETFn4LwFX9AzaXJYmLCR6hqruUvp2I9epNSegsXuvFLELsbnbNSgYDvNqThIbnHgsaM9LvZGG5HET9XgIRIdizlnRfywBzKVwmqBGeXn8z5ebNnYb5XjOYEwExOJ8=,iv:BRrZAz3BHOHfCG3l73BwMDYwubVKw5spzD9kDs1qTXI=,tag:54zZJqhf46Ixh4w6+hvOeA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
