apiVersion: batch/v1
kind: Job
metadata:
  name: homelab-api-migrate
  namespace: homelab-api
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: ghcr.io/wlodzimierrr/homelab-api:sha-b0d0b7160a711d00caa82e90c97ea0be68c20b19
