apiVersion: apps/v1
kind: Deployment
metadata:
  name: homelab-api
  namespace: homelab-api
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: api
          image: ghcr.io/wlodzimierrr/homelab-api:sha-9ed600ef70d36ff8472c2115061da3aaf9c1c74c
          env:
            - name: APP_ENV
              value: dev
            - name: LOG_LEVEL
              value: debug
