apiVersion: batch/v1
kind: CronJob
metadata:
  name: homelab-api-catalog-sync
  namespace: homelab-api
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: catalog-sync
              image: ghcr.io/wlodzimierrr/homelab-api:sha-f9ab61b753a4b5571652af24938beeba484dbe6f
