apiVersion: apps/v1
kind: Deployment
metadata:
  name: homelab-api
  namespace: homelab-api
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: api
          image: ghcr.io/wlodzimierrr/homelab-api:sha-18a478280e04ae769b11220587e0f121bf4e6fb3
          env:
            - name: APP_ENV
              value: dev
            - name: LOG_LEVEL
              value: debug
