apiVersion: apps/v1
kind: Deployment
metadata:
  name: homelab-api
  namespace: homelab-api
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: api
          image: ghcr.io/wlodzimierrr/homelab-api:sha-70176d838d826eaf44260348042fcb1e6d783a07
          env:
            - name: APP_ENV
              value: dev
            - name: LOG_LEVEL
              value: debug
