apiVersion: batch/v1
kind: Job
metadata:
  name: homelab-api-migrate
  namespace: homelab-api
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: ghcr.io/wlodzimierrr/homelab-api:sha-9ed600ef70d36ff8472c2115061da3aaf9c1c74c
