apiVersion: v1
kind: Secret
metadata:
    name: homelab-api-postgres
    namespace: homelab-api
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:m1H/yY5zxg==,iv:ut08FVY2ahC5/rlOo9SiXaQ8zIY/w5EEokOkNl1lwQE=,tag:ynNsooNSSxz/WQGofEJVgA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:PFiwoBE7XA==,iv:aTPIuukOG31+XraH85A2wrUQ697tNjr2mw06ArDiZ7I=,tag:IwWnDAZpk8qfVooc8PT1xg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:0mF0oj2gnPU=,iv:bpMi1Tu1m7LFymrhsV8DhO51df9BBz8oaKtahf+NyH4=,tag:SPicAYXdKv8IxQKPyduGXA==,type:str]
sops:
    age:
        - recipient: age1ufd3ltyyp6pwjsxp3teszwyf24scyu9jwszhyl3gzu2eh52wjyys7v8una
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBS2UxYVZlNVpWVzlMS1FR
            MWNjZmpMWUU5RDE5TmF2UkNXQ2VrYWpuUkFNCkNoUjYydnd1Q2hYTUU0Zzlub09U
            THQxTEVHTnZXU3pUdHAxVjNxVllITFEKLS0tIDZoTHlzU2N4RGRYU3EzN3cyS1pY
            MExvR3g1RGdKY2RLTzczSW93NUpvUXMKl1frTX2cjOGusu5xTOmBCtyFPLwBCDwJ
            S0+4CBeNLmcAMjg9v2Gz7ImG9ZDXxxtScfVgVIk52H3iLt/Vfr2sAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T17:03:19Z"
    mac: ENC[AES256_GCM,data:nJGcjClM0Rc4lFvxkB0ho2SgPXlYXHwOvZHgQb2o6mK2YTzoagHFoXRMYYijN53Zz0kT5syVb2nQQJt6Yss6sErFDyfsE0gPZCnj2rLHi1UYqX53dYY1Elvdukz7zVnA9U3mdlQkxKBSvUkesw7/c2lzC5+AByPbnyG/H/EmMvk=,iv:MRZnPlmaIw7bl1yRsLEeXF9nfIBbCvIj5dzPiykTyzA=,tag:pEkvsHtVC0YsXb4YgM+Icg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
