apiVersion: v1
kind: Secret
metadata:
    name: homelab-wordpress-wordpress-db
    namespace: homelab-wordpress
type: Opaque
stringData:
    WORDPRESS_DB_USER: ENC[AES256_GCM,data:f6tuBv3qOb71,iv:AF1kbbe8D1uigEwZpsOfU3gvlIrqGjhGNiF0eK7zXos=,tag:wk+UQ3Gyus1nIpcs7BRXww==,type:str]
    WORDPRESS_DB_PASSWORD: ENC[AES256_GCM,data:PjEdcR12IsF1C/bzcO9QfaH4dM9buuIpsGz+bQwGU0E=,iv:3DxYIJpwiqD89XT9GPeWDylkIQq1bkaX6ANJlzgQmHE=,tag:6YuD8vs5m3HJw4uJNWtp9A==,type:str]
    WORDPRESS_DB_NAME: ENC[AES256_GCM,data:l8qBPHdGcRFK,iv:A1xn5S7tVfs4USHrfH7Uw/O0oV9F7NtrxhHTAFsCrog=,tag:1ChLPqg+RgMp6qNeNsTMKA==,type:str]
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:J5AjzDPEzMv8JOWpk6qmK2ZPgK5QTR9+8VfDt/r13gQ=,iv:G9dDT/pTr1Vf00Ttt1KW4lqdHkrjdbeVrfddmxrKpHc=,tag:0xpbUqMFQpgrPt6/yvxB5w==,type:str]
sops:
    age:
        - recipient: age1ufd3ltyyp6pwjsxp3teszwyf24scyu9jwszhyl3gzu2eh52wjyys7v8una
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvbjBPSVlycnBSVjY1RVhM
            WTlZM1c5OS9JaWNNZU1jYityRGpzTUsxTFJJCmZPSVJyb2RTSkYzWDYxVzFOV1dU
            akxlVjZQcEU5bjVVVCs0cHR0ZEdYYWcKLS0tIFQvbDFhaHRJYXkwaU42bmdRc09n
            ZmlHWm1RVDU3NDRJOUt4QVU4QkFzQ0EKiQ+J5LOvDB4YezBMdRP20DhBh4Tf0QFD
            J5/4WqTS2MjhEYvFgaU+GsObruFfZufDDGlWbjwZ+b1GcOMGsSstlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T13:36:32Z"
    mac: ENC[AES256_GCM,data:Rxc8pUN2cY/HA/IuXSqv3B7FvksYsD/erxlOajHb+Slw90Z7oJa8mzh4a7QS6V7b+qInXYzq1hd9lKACMLw2UI4MRzEsWk1HzTA+HhOQOy+ksvAvwNkXCFPMr1ETLAMRWNMEhOB7zB1RfxRed7Bj8ca/crrl12ZrfL+zu2i5t9s=,iv:jR9Zrc51sSViaMCI8OI/3INEcQu2jg6oei42aTR7DnI=,tag:d5+z26Upcr0xzUx92H5Lww==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
