apiVersion: v1
kind: ServiceAccount
metadata:
  name: comparebuilding-web
  namespace: comparebuilding-web
  labels:
    app.kubernetes.io/name: comparebuilding-web
imagePullSecrets:
  - name: ghcr-pull-secret
