apiVersion: apps/v1
kind: Deployment
metadata:
  name: comparebuilding-web
  namespace: comparebuilding-web
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: app
          image: ghcr.io/wlodzimierrr/compare_frontend:sha-cb1e51634fee85e049a349b80abd0b7e3ad2a05d
          imagePullPolicy: Always
          env:
            - name: APP_ENV
              value: dev
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 256Mi
