apiVersion: v1
kind: Secret
metadata:
  name: homelab-api-postgres
  namespace: homelab-api
  labels:
    app.kubernetes.io/name: homelab-api
    app.kubernetes.io/component: postgres
type: Opaque
stringData:
  POSTGRES_DB: homelab
  POSTGRES_USER: homelab
  POSTGRES_PASSWORD: change-me
