apiVersion: v1
kind: Service
metadata:
  name: homelab-api-postgres
  namespace: homelab-api
  labels:
    app.kubernetes.io/name: homelab-api
    app.kubernetes.io/component: postgres
spec:
  selector:
    app.kubernetes.io/name: homelab-api
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
