apiVersion: v1
kind: Secret
metadata:
    name: homelab-api-postgres
    namespace: homelab-api
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:rxyofQqtEg==,iv:PVPbZjKbp1OtbAvpwGgMdVNngk0zp8SlXHgfMdUMZb4=,tag:5OGbEj++Jvz1K1qVOf1I7w==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:7Cm6U4bkWg==,iv:5qX1U7dM1D+vY1DoSyHFkk8lCWwJCS5NgACCDdarKBg=,tag:uxNri/Gbg2Nw6Ql82f+gAw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:hNVQFDT8PKE=,iv:jrJatF+9U/FkdSspt/0SidBo/qB3aqtUeoad4cO7FwI=,tag:1lVpxTVYgyZCXGf/xUnC+Q==,type:str]
sops:
    age:
        - recipient: age1ufd3ltyyp6pwjsxp3teszwyf24scyu9jwszhyl3gzu2eh52wjyys7v8una
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQeTREb3Zzcy8zbWp6UTJN
            Wml5NVU5Y2V4bFR5TEFNMjdIY3pPQTBoWUE0Cmk2L1NSWDhqYWVEbi9OU1hSanF4
            enVtdFFXaTg4T01LRldxcitHNTIvYWcKLS0tIDg4dytyRDlodDhUVE56MkJyTnJv
            dXcwUjBHSTl2WXowSEkweEQ4SlJoelUKgRjrNLku9TxBWBfgYKifzD26hGhuB1XR
            ttfSr1lAlICjtNf9YO7te8bYlEMggGfBmNmOf/FI+YJDF1NLuHZYRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T17:03:33Z"
    mac: ENC[AES256_GCM,data:8GsckNswW8uauqjN+Y0/r4GkoNBopA4zIwgAjMNPc3slgOq7p21M35UUmUuXPCYsdAn/DEixWNBbNampAW13DIifCN8kCCXGmKDZtHWs5MLu9VRvKC5oqnPWyG4lCJ5Vl0LyrFd44P0bIF9RI29iSQxAxvPReq+IV6DdaZwb/gM=,iv:1TMJUDLZ8SKal3aDLYSBAsuW0iE1RMyBUv+IWYR/KkE=,tag:LQ4x9r+FsMMrJ4sWu8uVAA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
