apiVersion: apps/v1
kind: Deployment
metadata:
  name: plan-10wk
  namespace: plan-10wk
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: web
          image: ghcr.io/wlodzimierrr/10wk_plan:sha-3d7b88d1f6ccaa5370c5393fbdfb1b6d42e92b1e
          imagePullPolicy: Always
          env:
            - name: APP_ENV
              value: dev
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 256Mi
